import React, { useState } from 'react';
import { FeatureHero, useIntegrationWorkspace, FhirPreview, Checklist, EnterpriseTable, StatusPill } from './advancedUtils.jsx';

export default function ABDMABHA({ currentHospital }) {
  const ws = useIntegrationWorkspace('Patient', 'abdm_abha_enabled');
  const [consent, setConsent] = useState({ patient_id:'', abha_number:'', consent_purpose:'OP Consultation', status:'granted' });
  const logs = ws.logs.filter(x=>x.system==='abdm_abha');
  return <section className="pageStack enterprise-feature-page"><FeatureHero eyebrow="ABDM / ABHA IDENTITY" title="ABDM/ABHA" hospital={currentHospital} description="Manage ABHA readiness, patient identity checks, consent logs and FHIR patient bundle previews for future ABDM integrations."><button className="ghostBtn" onClick={()=>ws.saveSetting(!ws.settingOn,'ABDM/ABHA readiness flag')}>{ws.settingOn?'Disable':'Enable'}</button></FeatureHero>
  <div className="advStatsGrid"><div className="stat-card"><span>Patient Resources</span><strong>{ws.fhir?.entry?.length||0}</strong><small>FHIR patients</small></div><div className="stat-card"><span>Consent Logs</span><strong>{logs.length}</strong><small>ABDM evidence</small></div><div className="stat-card"><span>ABHA Field</span><strong>Ready</strong><small>dynamic/custom field supported</small></div><div className="stat-card"><span>Status</span><strong>{ws.settingOn?'ON':'OFF'}</strong><small>feature flag</small></div></div>
  <div className="grid twoCols"><form className="card enterprise-module-card form" onSubmit={(e)=>{e.preventDefault(); ws.createLog({system:'abdm_abha',direction:'inbound',resource_type:'Consent',resource_id:consent.patient_id,method:'CONSENT',endpoint:'/abdm/consents',request_payload:consent,status:'success'});}}><h3>Create Consent / ABHA Readiness Log</h3><label><span>Patient ID</span><input value={consent.patient_id} onChange={e=>setConsent({...consent,patient_id:e.target.value})} required /></label><label><span>ABHA Number / Address</span><input value={consent.abha_number} onChange={e=>setConsent({...consent,abha_number:e.target.value})} placeholder="ABHA ID or address" /></label><label><span>Consent purpose</span><input value={consent.consent_purpose} onChange={e=>setConsent({...consent,consent_purpose:e.target.value})}/></label><label><span>Status</span><select value={consent.status} onChange={e=>setConsent({...consent,status:e.target.value})}><option>requested</option><option>granted</option><option>revoked</option><option>expired</option></select></label><button>Save Consent Log</button></form><FhirPreview workspace={ws} title="ABDM Patient Bundle Preview" /></div>
  <Checklist items={['ABHA number captured as patient/custom field','Consent event log available','FHIR patient bundle available','Identity verification audit ready','Future ABDM gateway mapping prepared']} />
  <EnterpriseTable title="ABDM / ABHA Consent Logs" rows={logs} columns={[{key:'created_at',label:'Time',render:r=>r.created_at?new Date(r.created_at).toLocaleString():'-'},{key:'resource_id',label:'Patient ID'},{key:'method',label:'Action'},{key:'request_payload',label:'Purpose',render:r=>r.request_payload?.consent_purpose||'-'},{key:'status',label:'Status',render:r=><StatusPill>{r.status}</StatusPill>}]} empty="No ABDM/ABHA logs yet. Save a consent readiness log." />
  </section>;
}
