import React, { useState } from 'react';
import { FeatureHero, useIntegrationWorkspace, Checklist, EnterpriseTable, StatusPill } from './advancedUtils.jsx';

export default function Biometric({ currentHospital }) {
  const ws = useIntegrationWorkspace('Patient', 'biometric_enabled');
  const [device, setDevice] = useState({ device_id:'BIO-001', location:'Main Reception', mode:'attendance', status:'online' });
  const [event, setEvent] = useState({ person_type:'staff', person_id:'', event_type:'check_in', device_id:'BIO-001' });
  const bioLogs = ws.logs.filter(x=>x.system==='biometric');
  return <section className="pageStack enterprise-feature-page"><FeatureHero eyebrow="BIOMETRIC IDENTITY" title="Biometric" hospital={currentHospital} description="Register biometric devices, test attendance/identity events and keep auditable logs for staff and patient verification."><button className="ghostBtn" onClick={()=>ws.saveSetting(!ws.settingOn,'Biometric readiness flag')}>{ws.settingOn?'Disable':'Enable'}</button></FeatureHero>
  <div className="advStatsGrid"><div className="stat-card"><span>Events</span><strong>{bioLogs.length}</strong><small>biometric logs</small></div><div className="stat-card"><span>Device</span><strong>{device.status}</strong><small>{device.device_id}</small></div><div className="stat-card"><span>Mode</span><strong>{device.mode}</strong><small>verification flow</small></div><div className="stat-card"><span>Status</span><strong>{ws.settingOn?'ON':'OFF'}</strong><small>feature flag</small></div></div>
  <div className="grid twoCols"><form className="card enterprise-module-card form" onSubmit={(e)=>{e.preventDefault(); ws.createLog({system:'biometric',direction:'inbound',resource_type:'Device',resource_id:device.device_id,method:'REGISTER',endpoint:'/biometric/devices',request_payload:device,status:'success'});}}><h3>Device Register</h3><label><span>Device ID</span><input value={device.device_id} onChange={e=>setDevice({...device,device_id:e.target.value})}/></label><label><span>Location</span><input value={device.location} onChange={e=>setDevice({...device,location:e.target.value})}/></label><label><span>Mode</span><select value={device.mode} onChange={e=>setDevice({...device,mode:e.target.value})}><option>attendance</option><option>patient_identity</option><option>staff_access</option></select></label><label><span>Status</span><select value={device.status} onChange={e=>setDevice({...device,status:e.target.value})}><option>online</option><option>offline</option><option>maintenance</option></select></label><button>Save Device Log</button></form><form className="card enterprise-module-card form" onSubmit={(e)=>{e.preventDefault(); ws.createLog({system:'biometric',direction:'inbound',resource_type:event.person_type,resource_id:event.person_id,method:event.event_type,endpoint:'/biometric/events',request_payload:event,status:'success'});}}><h3>Test Biometric Event</h3><label><span>Person type</span><select value={event.person_type} onChange={e=>setEvent({...event,person_type:e.target.value})}><option>staff</option><option>patient</option><option>doctor</option></select></label><label><span>Person ID</span><input value={event.person_id} onChange={e=>setEvent({...event,person_id:e.target.value})} placeholder="user/patient/doctor id" /></label><label><span>Event type</span><select value={event.event_type} onChange={e=>setEvent({...event,event_type:e.target.value})}><option>check_in</option><option>check_out</option><option>identity_verified</option><option>access_denied</option></select></label><label><span>Device ID</span><input value={event.device_id} onChange={e=>setEvent({...event,device_id:e.target.value})}/></label><button>Save Event</button></form></div>
  <Checklist items={['Device registration log','Staff attendance event','Patient identity verification','Audit log evidence','Manual fallback available']} />
  <EnterpriseTable title="Biometric Event Logs" rows={bioLogs} columns={[{key:'created_at',label:'Time',render:r=>r.created_at?new Date(r.created_at).toLocaleString():'-'},{key:'resource_type',label:'Type'},{key:'resource_id',label:'Person/Device'},{key:'method',label:'Event'},{key:'status',label:'Status',render:r=><StatusPill type={r.status==='failed'?'danger':'success'}>{r.status}</StatusPill>}]} empty="No biometric events yet. Save a device or test event." />
  </section>;
}
