import React, { useState } from 'react';
import { FeatureHero, useIntegrationWorkspace, IntegrationKeyPanel, FhirPreview, Checklist, EnterpriseTable, StatusPill } from './advancedUtils.jsx';

export default function ERPTally({ currentHospital }) {
  const ws = useIntegrationWorkspace('Invoice', 'erp_tally_enabled');
  const [map, setMap] = useState({ ledger:'Hospital Sales', tax_ledger:'GST Output', payment_ledger:'Cash/Bank', export_format:'json' });
  const erpLogs = ws.logs.filter(x=>x.system==='erp_tally');
  return <section className="pageStack enterprise-feature-page"><FeatureHero eyebrow="ERP / TALLY EXPORT" title="ERP/Tally" hospital={currentHospital} description="Prepare invoice, payment and ledger export flows for Tally/ERP accounting systems without touching core billing data."><button className="ghostBtn" onClick={()=>ws.saveSetting(!ws.settingOn,'ERP/Tally readiness flag')}>{ws.settingOn?'Disable':'Enable'}</button></FeatureHero>
  <div className="advStatsGrid"><div className="stat-card"><span>Exports</span><strong>{erpLogs.length}</strong><small>export logs</small></div><div className="stat-card"><span>Invoice Resources</span><strong>{ws.fhir?.entry?.length||0}</strong><small>ready for export</small></div><div className="stat-card"><span>Format</span><strong>{map.export_format.toUpperCase()}</strong><small>selected export</small></div><div className="stat-card"><span>Status</span><strong>{ws.settingOn?'ON':'OFF'}</strong><small>feature flag</small></div></div>
  <div className="grid twoCols"><form className="card enterprise-module-card form" onSubmit={(e)=>{e.preventDefault(); ws.createLog({system:'erp_tally',direction:'outbound',resource_type:'Invoice',method:'EXPORT',endpoint:'/erp/tally/export',request_payload:map,response_payload:{format:map.export_format,status:'queued'},status:'success'});}}><h3>Ledger Mapping</h3><label><span>Sales ledger</span><input value={map.ledger} onChange={e=>setMap({...map,ledger:e.target.value})}/></label><label><span>Tax ledger</span><input value={map.tax_ledger} onChange={e=>setMap({...map,tax_ledger:e.target.value})}/></label><label><span>Payment ledger</span><input value={map.payment_ledger} onChange={e=>setMap({...map,payment_ledger:e.target.value})}/></label><label><span>Export format</span><select value={map.export_format} onChange={e=>setMap({...map,export_format:e.target.value})}><option>json</option><option>csv</option><option>xml</option></select></label><button>Run Test Export</button></form><IntegrationKeyPanel title="Create ERP API Key" defaultName="ERP/Tally Export Key" scopes={['invoice.read','payment.read','erp.export']} workspace={ws}/></div>
  <div className="grid twoCols"><FhirPreview workspace={ws} title="Invoice Export Preview" /><Checklist items={['Invoice resource export','Ledger mapping stored','Payment mode mapping ready','Export audit log created','Tally-compatible payload preview']} /></div>
  <EnterpriseTable title="ERP/Tally Export Logs" rows={erpLogs} columns={[{key:'created_at',label:'Time',render:r=>r.created_at?new Date(r.created_at).toLocaleString():'-'},{key:'resource_type',label:'Resource'},{key:'method',label:'Action'},{key:'endpoint',label:'Endpoint'},{key:'status',label:'Status',render:r=><StatusPill>{r.status}</StatusPill>}]} empty="No ERP export logs yet. Run a test export." />
  </section>;
}
