import React, { useState } from 'react';
import { FeatureHero, useIntegrationWorkspace, IntegrationKeyPanel, WebhookPanel, FhirPreview, Checklist, EnterpriseTable, commonColumns } from './advancedUtils.jsx';

export default function HL7Ready({ currentHospital }) {
  const ws = useIntegrationWorkspace('Patient', 'hl7_ready_enabled');
  const [test, setTest] = useState({ message_type: 'ADT^A01', patient_ref: '', endpoint: '/hl7/adt' });
  return <section className="pageStack enterprise-feature-page">
    <FeatureHero eyebrow="HL7 INTEROPERABILITY" title="HL7 Ready" hospital={currentHospital} description="Configure HL7 readiness for ADT, ORM and ORU style workflows, integration keys, webhooks and message audit logs."><button className="ghostBtn" onClick={() => ws.saveSetting(!ws.settingOn, 'HL7 readiness flag')}>{ws.settingOn ? 'Disable' : 'Enable'}</button></FeatureHero>
    <div className="advStatsGrid"><div className="stat-card"><span>Message Logs</span><strong>{ws.logs.filter(x=>x.system==='hl7').length}</strong><small>HL7 activity</small></div><div className="stat-card"><span>API Keys</span><strong>{ws.apiKeys.length}</strong><small>integration credentials</small></div><div className="stat-card"><span>Webhooks</span><strong>{ws.webhooks.length}</strong><small>event endpoints</small></div><div className="stat-card"><span>Status</span><strong>{ws.settingOn?'ON':'OFF'}</strong><small>hospital feature flag</small></div></div>
    <div className="grid twoCols"><IntegrationKeyPanel title="Create HL7 API Key" defaultName="HL7 Integration Key" scopes={['hl7.read','hl7.write','fhir.read']} workspace={ws}/><WebhookPanel title="HL7 Webhook Endpoint" defaultEvents="patient.created,appointment.created,lab.approved" workspace={ws}/></div>
    <div className="grid twoCols"><form className="card enterprise-module-card form" onSubmit={(e)=>{e.preventDefault(); ws.createLog({ system:'hl7', direction:'outbound', resource_type:test.message_type, method:'POST', endpoint:test.endpoint, request_payload:test, response_payload:{ack:'AA'}, status:'success', status_code:200 });}}><h3>Send Test HL7 Event</h3><label><span>Message type</span><select value={test.message_type} onChange={e=>setTest({...test,message_type:e.target.value})}><option>ADT^A01</option><option>ADT^A04</option><option>ORM^O01</option><option>ORU^R01</option></select></label><label><span>Patient / Visit reference</span><input value={test.patient_ref} onChange={e=>setTest({...test,patient_ref:e.target.value})} placeholder="PAT-001 / appointment id" /></label><label><span>Endpoint</span><input value={test.endpoint} onChange={e=>setTest({...test,endpoint:e.target.value})}/></label><button>Save Test Message</button></form><FhirPreview workspace={ws} title="HL7/FHIR Resource Preview" /></div>
    <Checklist items={['ADT patient registration events', 'ORM order event readiness', 'ORU result event readiness', 'Message audit trail stored', 'FHIR fallback export available']} />
    <EnterpriseTable title="HL7 Message Logs" rows={ws.logs.filter(x=>!x.system || x.system==='hl7' || x.system==='fhir')} columns={commonColumns.logs} empty="No HL7 logs yet. Send a test message or call FHIR preview." />
  </section>;
}
