import React, { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { radiologyApi } from '../api';
import { FeatureHero, useIntegrationWorkspace, IntegrationKeyPanel, FhirPreview, Checklist, EnterpriseTable, StatusPill } from './advancedUtils.jsx';

export default function PACSDicom({ currentHospital }) {
  const ws = useIntegrationWorkspace('DiagnosticReport', 'pacs_dicom_enabled');
  const [orders, setOrders] = useState([]);
  const [form, setForm] = useState({ patient_id:'', doctor_id:'', scan_name:'', modality:'CT', body_part:'', dicom_study_id:'', pacs_viewer_url:'' });
  async function loadOrders(){ try{ const {data}=await radiologyApi.list(); setOrders(Array.isArray(data)?data:[]);}catch{ setOrders([]);} }
  useEffect(()=>{ loadOrders(); },[]);
  async function create(e){ e.preventDefault(); try{ await radiologyApi.create(form); toast.success('Radiology/DICOM order created'); setForm({ patient_id:'', doctor_id:'', scan_name:'', modality:'CT', body_part:'', dicom_study_id:'', pacs_viewer_url:'' }); loadOrders(); }catch(err){ toast.error(err.response?.data?.message||'Order creation failed'); } }
  return <section className="pageStack enterprise-feature-page"><FeatureHero eyebrow="PACS / DICOM WORKLIST" title="PACS/DICOM" hospital={currentHospital} description="Manage radiology studies, DICOM study IDs, PACS viewer URLs, reports and integration credentials."><button className="ghostBtn" onClick={()=>ws.saveSetting(!ws.settingOn,'PACS/DICOM readiness flag')}>{ws.settingOn?'Disable':'Enable'}</button></FeatureHero>
  <div className="advStatsGrid"><div className="stat-card"><span>Studies</span><strong>{orders.length}</strong><small>radiology orders</small></div><div className="stat-card"><span>DICOM IDs</span><strong>{orders.filter(o=>o.dicom_study_id).length}</strong><small>mapped studies</small></div><div className="stat-card"><span>Reports</span><strong>{orders.filter(o=>o.report_url||o.pacs_viewer_url).length}</strong><small>linked reports/viewers</small></div><div className="stat-card"><span>Status</span><strong>{ws.settingOn?'ON':'OFF'}</strong><small>feature flag</small></div></div>
  <div className="grid twoCols"><form className="card enterprise-module-card form" onSubmit={create}><h3>Create DICOM Study</h3><label><span>Patient ID</span><input value={form.patient_id} onChange={e=>setForm({...form,patient_id:e.target.value})} required /></label><label><span>Doctor ID</span><input value={form.doctor_id} onChange={e=>setForm({...form,doctor_id:e.target.value})}/></label><label><span>Scan name</span><input value={form.scan_name} onChange={e=>setForm({...form,scan_name:e.target.value})} required /></label><label><span>Modality</span><select value={form.modality} onChange={e=>setForm({...form,modality:e.target.value})}><option>XRAY</option><option>CT</option><option>MRI</option><option>USG</option><option>ECG</option></select></label><label><span>Body part</span><input value={form.body_part} onChange={e=>setForm({...form,body_part:e.target.value})}/></label><label><span>DICOM Study ID</span><input value={form.dicom_study_id} onChange={e=>setForm({...form,dicom_study_id:e.target.value})}/></label><label><span>PACS Viewer URL</span><input value={form.pacs_viewer_url} onChange={e=>setForm({...form,pacs_viewer_url:e.target.value})}/></label><button>Create Study</button></form><IntegrationKeyPanel title="Create PACS API Key" defaultName="PACS DICOM Key" scopes={['pacs.read','dicom.write','fhir.read']} workspace={ws}/></div>
  <EnterpriseTable title="Radiology Study Worklist" rows={orders} columns={[{key:'id',label:'ID',render:r=>`#${r.id}`},{key:'patient_id',label:'Patient'},{key:'scan_name',label:'Study'},{key:'modality',label:'Modality'},{key:'dicom_study_id',label:'DICOM ID'},{key:'pacs_viewer_url',label:'Viewer',render:r=>r.pacs_viewer_url?<a href={r.pacs_viewer_url} target="_blank">Open</a>:'-'},{key:'status',label:'Status',render:r=><StatusPill>{r.status||r.approval_status||'ordered'}</StatusPill>}]} empty="No radiology studies yet. Create one from the DICOM form." />
  <div className="grid twoCols"><Checklist items={['DICOM study ID captured','PACS viewer URL stored','Radiology report linked','FHIR DiagnosticReport export available']} /><FhirPreview workspace={ws} title="DiagnosticReport Preview" /></div></section>;
}
