import React, { useState } from 'react';
import toast from 'react-hot-toast';
import { auditApi } from '../api';
import { FeatureHero, useIntegrationWorkspace, Checklist, EnterpriseTable, StatusPill } from './advancedUtils.jsx';

export default function TwoFactorSecurity({ currentHospital }) {
  const ws = useIntegrationWorkspace('Patient', 'two_factor_auth_enabled');
  const [policy, setPolicy] = useState({ method:'email_otp', enforce_for_admins:'true', session_timeout_minutes:'60', recovery_codes:'enabled' });
  async function savePolicy(e){ e.preventDefault(); try{ await Promise.all(Object.entries(policy).map(([k,v])=>auditApi.saveSetting(`2fa_${k}`,{value:String(v),category:'two_factor_auth',description:`2FA ${k}`}))); await ws.saveSetting(true,'Hospital 2FA master flag'); toast.success('2FA policy saved'); }catch(err){ toast.error(err.response?.data?.message||'2FA policy save failed'); } }
  return <section className="pageStack enterprise-feature-page"><FeatureHero eyebrow="ACCOUNT SECURITY" title="2FA Security" hospital={currentHospital} description="Configure hospital-level two-factor policy, enforcement settings and review login history evidence."><button className="ghostBtn" onClick={()=>ws.saveSetting(!ws.settingOn,'2FA hospital feature flag')}>{ws.settingOn?'Disable':'Enable'}</button></FeatureHero>
  <div className="advStatsGrid"><div className="stat-card"><span>Login Events</span><strong>{ws.loginHistory.length}</strong><small>tracked auth events</small></div><div className="stat-card"><span>Failed Logins</span><strong>{ws.loginHistory.filter(x=>x.status==='failed').length}</strong><small>risk signals</small></div><div className="stat-card"><span>Method</span><strong>{policy.method.replace('_',' ')}</strong><small>selected OTP flow</small></div><div className="stat-card"><span>Status</span><strong>{ws.settingOn?'ON':'OFF'}</strong><small>feature flag</small></div></div>
  <div className="grid twoCols"><form className="card enterprise-module-card form" onSubmit={savePolicy}><h3>2FA Policy</h3><label><span>OTP method</span><select value={policy.method} onChange={e=>setPolicy({...policy,method:e.target.value})}><option>email_otp</option><option>sms_otp</option><option>authenticator_app</option></select></label><label><span>Enforce for admins</span><select value={policy.enforce_for_admins} onChange={e=>setPolicy({...policy,enforce_for_admins:e.target.value})}><option>true</option><option>false</option></select></label><label><span>Session timeout minutes</span><input type="number" value={policy.session_timeout_minutes} onChange={e=>setPolicy({...policy,session_timeout_minutes:e.target.value})}/></label><label><span>Recovery codes</span><select value={policy.recovery_codes} onChange={e=>setPolicy({...policy,recovery_codes:e.target.value})}><option>enabled</option><option>disabled</option></select></label><button>Save 2FA Policy</button></form><Checklist items={['Admin 2FA enforcement','OTP method configured','Login history reviewed','Recovery flow defined','Security audit evidence available']} /></div>
  <EnterpriseTable title="Login History" rows={ws.loginHistory} columns={[{key:'logged_at',label:'Time',render:r=>r.logged_at?new Date(r.logged_at).toLocaleString():'-'},{key:'email',label:'Email'},{key:'role',label:'Role'},{key:'ip_address',label:'IP'},{key:'status',label:'Status',render:r=><StatusPill type={r.status==='failed'?'danger':'success'}>{r.status}</StatusPill>}]} empty="No login history found yet. Login events will appear after users sign in." />
  <EnterpriseTable title="2FA Security Settings" rows={ws.settings.filter(x=>x.category==='two_factor_auth'||x.setting_key?.includes('2fa')||x.setting_key==='two_factor_auth_enabled')} columns={[{key:'setting_key',label:'Key'},{key:'setting_value',label:'Value'},{key:'category',label:'Category'},{key:'description',label:'Description'}]} empty="No 2FA settings yet. Save the policy above." />
  </section>;
}
