import api from './client';
export const integrationApi = {
  summary: () => api.get('/integration/summary'),
  keys: () => api.get('/integration/api-keys'),
  createKey: (payload) => api.post('/integration/api-keys', payload),
  updateKey: (id, payload) => api.patch(`/integration/api-keys/${id}`, payload),
  logs: () => api.get('/integration/logs'),
  createLog: (payload) => api.post('/integration/logs', payload),
  webhooks: () => api.get('/integration/webhooks'),
  createWebhook: (payload) => api.post('/integration/webhooks', payload),
  createWebhookEvent: (payload) => api.post('/integration/webhook-events', payload),
  fhir: (resource) => api.get(`/fhir/${resource}`),
  hl7Summary: () => api.get('/hl7/summary'),
  hl7Messages: () => api.get('/hl7/messages'),
  hl7Generate: (payload) => api.post('/hl7/generate', payload),
  hl7Parse: (payload) => api.post('/hl7/parse', payload),
  hl7Queue: (payload) => api.post('/hl7/messages', payload),
  hl7Ack: (id, payload) => api.post(`/hl7/messages/${id}/ack`, payload),
  hl7Retry: (id, payload) => api.post(`/hl7/messages/${id}/retry`, payload),
  abdmSummary: () => api.get('/abdm/summary'),
  abdmReadiness: () => api.get('/abdm/readiness'),
  abdmVerifyIdentity: (payload) => api.post('/abdm/identity/verify', payload),
  abdmConsents: () => api.get('/abdm/consents'),
  abdmCreateConsent: (payload) => api.post('/abdm/consents', payload),
  abdmUpdateConsentStatus: (id, payload) => api.patch(`/abdm/consents/${id}/status`, payload),
  abdmCareContexts: () => api.get('/abdm/care-contexts'),
  abdmCreateCareContext: (payload) => api.post('/abdm/care-contexts', payload),
};
