import api from './client';

export const saasApi = {
  overview: () => api.get('/saas/overview'),
  exportTenants: () => api.get('/saas/tenants/export.csv', { responseType: 'blob' }),
  updateSubscription: (id, data) => api.patch(`/tenants/${id}/subscription`, data),
  lifecycle: (id, data) => api.post(`/tenants/${id}/lifecycle/${data.action}`, data),
  billingSummary: () => api.get('/saas/billing/summary'),
  invoices: (params = {}) => api.get('/saas/invoices', { params }),
  generateInvoice: (data) => api.post('/saas/invoices/generate', data),
  updateInvoiceStatus: (id, data) => api.patch(`/saas/invoices/${id}/status`, data),
  recordPayment: (id, data) => api.post(`/saas/invoices/${id}/payments`, data),
  createPaymentLink: (id, data = {}) => api.post(`/saas/invoices/${id}/payment-link`, data),
  paymentIntents: (params = {}) => api.get('/saas/payment-intents', { params }),
  paymentGateways: () => api.get('/saas/payment-gateways/providers'),
  settlementSummary: (params = {}) => api.get('/saas/settlements/summary', { params }),
  subscriptionAnalytics: () => api.get('/saas/analytics/subscriptions'),
  settlements: (params = {}) => api.get('/saas/settlements', { params }),
  reconcileSettlement: (data) => api.post('/saas/settlements/reconcile', data),
  exportSettlements: () => api.get('/saas/settlements/export.csv', { responseType: 'blob' }),
  confirmPaymentIntent: (id, data = {}) => api.post(`/saas/payment-intents/${id}/confirm`, data),
  markOverdueInvoices: () => api.post('/saas/invoices/mark-overdue'),
  exportInvoices: () => api.get('/saas/invoices/export.csv', { responseType: 'blob' }),
  businessPlans: () => api.get('/saas/business/plans'),
  createBusinessPlan: (data) => api.post('/saas/business/plans', data),
  updateBusinessPlan: (planId, data) => api.patch(`/saas/business/plans/${planId}`, data),
  licenseStatus: () => api.get('/saas/license/status'),
  onboardHospital: (data) => api.post('/saas/onboarding/hospitals', data),
  onboardingChecklist: () => api.get('/saas/onboarding/checklist'),
  tenantDbOverview: () => api.get('/tenant-databases/overview'),
  provisionTenantDb: (hospitalId, data = {}) => api.post(`/tenant-databases/${hospitalId}/provision`, data),
  backupTenantDb: (hospitalId, data = {}) => api.post(`/tenant-databases/${hospitalId}/backup`, data),
  tenantBackups: (params = {}) => api.get('/tenant-databases/backups', { params }),
  verifyTenantBackup: (id) => api.post(`/tenant-databases/backups/${id}/verify`),
  knowledgeBase: (params = {}) => api.get('/saas/knowledge-base', { params }),
  createKnowledgeArticle: (data) => api.post('/saas/knowledge-base', data),
  updateKnowledgeArticle: (id, data) => api.patch(`/saas/knowledge-base/${id}`, data),
  publishKnowledgeArticle: (id) => api.post(`/saas/knowledge-base/${id}/publish`),
  archiveKnowledgeArticle: (id) => api.post(`/saas/knowledge-base/${id}/archive`),
  publicKnowledgeBase: (params = {}) => api.get('/saas/knowledge-base/public', { params }),
  publicKnowledgeArticle: (slug) => api.get(`/saas/knowledge-base/public/${slug}`),
};
